name: syncthing-gael
version: "v1.29.3"
base: core24
summary: Open Source Continuous File Synchronization
description: |
  Syncthing is a continuous file synchronization program. It synchronizes files between 
  two or more computers in real time, safely protected from prying eyes. Your data is 
  your data alone and you deserve to choose where it is stored, whether it is shared with 
  some third party, and how it's transmitted over the internet.

grade: stable
confinement: strict

platforms:
  arm64:
  armhf:
  amd64:
  ppc64el:
  s390x:

license: "MPL-2.0"

apps:
  syncthingd:
    command: syncthingd.sh
    daemon: simple
    environment:
      HOME: ${SNAP_COMMON}
    plugs:
    - home
    - network
    - network-bind
    - removable-media

parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    stage:
      - syncthingd.sh

  app:
    plugin: go
    source: https://github.com/syncthing/syncthing.git
    source-tag: v1.29.3
    source-type: git
    build-snaps:
      - go/1.23/stable
    override-build: |
      ARCH=$(echo ${CRAFT_ARCH_BUILD_FOR}|sed -e "s/armhf/arm/" -e "s/ppc64el/ppc64le/")

      go run build.go -no-upgrade -goos linux -goarch ${ARCH} build
      
      mkdir -p ../install/bin
      cp syncthing ../install/bin/syncthing
