name: syncthing-gael
version: "v1.27.5-rc.1"
base: core22
summary: Open Source Continuous File Synchronization
description: |
  Syncthing is a continuous file synchronization program. It synchronizes files between 
  two or more computers in real time, safely protected from prying eyes. Your data is 
  your data alone and you deserve to choose where it is stored, whether it is shared with 
  some third party, and how it's transmitted over the internet.

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

license: "MPL-2.0"

apps:
  syncthingd:
    command: syncthingd.sh
    daemon: simple
    environment:
      HOME: ${SNAP_COMMON}
    plugs:
    - home
    - network
    - network-bind
    - removable-media

parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    stage:
      - syncthingd.sh

  app:
    plugin: go
    source: https://github.com/syncthing/syncthing.git
    source-tag: v1.27.5-rc.1
    source-type: git
    build-snaps:
      - go
    override-build: |
      ARR="$(echo '${SNAPCRAFT_ARCH_TRIPLET}' | cut -d'-' -f1)"
      ARCH=$(echo ${ARR}|sed -e "s/armhf/arm/" -e "s/aarch/arm/" -e "s/x86_/amd/")
      #
      go run build.go -no-upgrade -goos linux -goarch ${ARCH} build
      mkdir -p ../install/bin
      cp syncthing ../install/bin/syncthing
