name: syncthing-gael
version: "1.22.2-rc.2"
base: core20
summary: Open Source Continuous File Synchronization
description: |
  Syncthing is a continuous file synchronization program. It synchronizes files between 
  two or more computers in real time, safely protected from prying eyes. Your data is 
  your data alone and you deserve to choose where it is stored, whether it is shared with 
  some third party, and how it's transmitted over the internet.

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

license: "MPL-2.0"

apps:
  syncthingd:
    command: syncthingd.sh
    daemon: simple
    environment:
      HOME: ${SNAP_COMMON}
    plugs:
    - home
    - network
    - network-bind
    - removable-media

parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    stage:
      - syncthingd.sh

  app:
    plugin: go
    source: https://github.com/syncthing/syncthing.git
    source-tag: v1.22.2-rc.2
    source-type: git
    build-packages:
      - build-essential
    override-build: |
      ARR="$(echo '${SNAPCRAFT_ARCH_TRIPLET}' | cut -d'-' -f1)"
      ARCH=$(echo ${ARR}|sed -e "s/armhf/arm/" -e "s/aarch/arm/" -e "s/x86_/amd/")
      #
      go run build.go -no-upgrade -goos linux -goarch ${ARCH} build
      mkdir -p ../install/bin
      cp syncthing ../install/bin/syncthing

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280#heading--cleanup-part
  #
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - app
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core20
    override-prime: |
      set -eux
      for snap in "core20"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

